---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
```

```{r}
library(p8105.datasets)
data("ny_noaa")
```

```{r}
library(p8105.datasets)
data("ny_noaa")

tidy_noaa = ny_noaa %>% 
  separate(date, into = c('year', 'month', 'date'), sep = '-') %>% 
  mutate(
    year = as.integer(year),
    month = month.name[as.integer(month)],
    day = as.integer(date),
    prcp = as.numeric(prcp)*0.1,
    tmax = as.numeric(tmax)*0.1,
    tmin = as.numeric(tmin)*0.1) %>%
  drop_na(tmin, tmax)  %>%
  filter(year == 2010 &
         month == "January")
```


Column {data-width=550}
-----------------------------------------------------------------------

### Chart A

```{r}
tidy_noaa %>%
  mutate(text_label = str_c("Month:", month, "\nDate:", date)) %>% 
  plot_ly(x = ~tmax, y = ~tmin, color = ~snwd,
          type = "scatter", mode = "markers",
          alpha = 0.5, text = ~text_label) %>% 
  layout(title = "Max Temperature vs. Min Temperature in January 2010",
         xaxis = list(title = "Max Temp (°C)"),
         yaxis = list(title = "Min Temp (°C)"))


```

Column {data-width=450}
-----------------------------------------------------------------------

### Chart B

```{r}
tidy_noaa %>% 
   plot_ly(y = ~tmax, color = ~date, 
           type = "box", colors = "viridis") %>% 
    layout(title = "Distribution of Max Temperature for Each Day in January 2010",
         xaxis = list(title = "Day"),
         yaxis = list(title = "Max Temp (°C)"))
```

### Chart C

```{r}
tidy_noaa %>% 
  plot_ly(x = ~date, y = ~snwd,
          type = "bar", color = "viridis") %>% 
  layout(title = "Total Amount of Snow Depth for Each Day in January 2010",
         xaxis = list(title = "Day"),
         yaxis = list(title = "Snow Depth (mm)"))
```

